### ISSUE TITLE
Typekit does not fonts when URL is localhost

### ISSUE THREAD

**Issue by jnmarcus** [overland-oakland/overland-oakland.github.io#2]
need to add 'localhost' to list of URLs Typekit will accept

**Comment by elmitche** [comment]
Nice work, Jamie! It's looking so good!

So I need to do some stuff, yes? What does that mean exactly "add
'localhost' to list of URLs Typekit will accept". I'm on skype for the rest
of the day, so ping me and maybe we could resolve that together.

Also we desperately need a less blah background image don't we? I'll look
into that...

Thanks! You da best!

Emma
